### ISSUE TITLE
Cannot find a resource matching firewall[default] (did you define it first?)

### ISSUE THREAD

**Issue by mcfiredrill** [chef-cookbooks/ufw#20]
I get the error `    Cannot find a resource matching firewall[default] (did you define it first?)` when trying to run the `ufw::default` recipe. Using the 1.0 version of this cookbook.

```
Recipe: ufw::default
  * apt_package[ufw] action install (up to date)
  * execute[ufw --force reset] action run
    - execute ufw --force reset
  * firewall[ufw] action install[2016-01-31T03:57:32-05:00] WARN: Cloning resource attributes for apt_package[ufw] from prior resource (CHEF-3694)
[2016-01-31T03:57:32-05:00] WARN: Previous apt_package[ufw]: /root/chef-solo/cookbooks-2/ufw/recipes/default.rb:21:in `from_file'
[2016-01-31T03:57:32-05:00] WARN: Current  apt_package[ufw]: /root/chef-solo/cookbooks-2/firewall/libraries/provider_firewall_ufw.rb:36:in `block (2 l
evels) in <class:FirewallUfw>'

    - install ufw, create template for /etc/default
  * apt_package[ufw] action install (up to date)
  * template[/etc/default/ufw] action create (up to date)
  * file[create empty /etc/default/ufw-chef.rules] action create (skipped due to not_if)
  * firewall_rule[ssh] action create
    
    ================================================================================
    Error executing action `create` on resource 'firewall_rule[ssh]'
    ================================================================================
    
    Chef::Exceptions::ResourceNotFound
    ----------------------------------
    Cannot find a resource matching firewall[default] (did you define it first?)
    
    Cookbook Trace:
    ---------------
    /root/chef-solo/cookbooks-2/firewall/libraries/provider_firewall_rule.rb:27:in `block in <class:FirewallRuleGeneric>'
    
    Resource Declaration:
    ---------------------
    # In /root/chef-solo/cookbooks-2/ufw/recipes/default.rb
    
     44:   firewall_rule 'ssh' do
     45:     port 22
     46:     action :create
     47:   end
     48: 
    
    Compiled Resource:
    ------------------
    # Declared in /root/chef-solo/cookbooks-2/ufw/recipes/default.rb:44:in `from_file'
    
    firewall_rule("ssh") do
      action [:create]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :firewall_rule
      cookbook_name :ufw
      recipe_name "default"
      port 22
      notify_firewall true
      firewall_name "default"
    end
```

```
cat /var/chef/cache/chef-stacktrace.out
Generated at 2016-01-31 03:57:32 -0500
Chef::Exceptions::ResourceNotFound: firewall_rule[ssh] (ufw::default line 44) had an error: Chef::Exceptions::ResourceNotFound: Cannot find a resource
 matching firewall[default] (did you define it first?)
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/resource_collection/resource_set.rb:63:in `lookup'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/resource_collection/resource_set.rb:142:in `block (2 levels) in find_resource_by_hash
'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/resource_collection/resource_set.rb:141:in `each'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/resource_collection/resource_set.rb:141:in `block in find_resource_by_hash'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/resource_collection/resource_set.rb:139:in `each'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/resource_collection/resource_set.rb:139:in `find_resource_by_hash'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/resource_collection/resource_set.rb:85:in `block in find'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/resource_collection/resource_set.rb:82:in `each'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/resource_collection/resource_set.rb:82:in `find'
/root/chef-solo/cookbooks-2/firewall/libraries/provider_firewall_rule.rb:27:in `block in <class:FirewallRuleGeneric>'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/provider/lwrp_base.rb:87:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/provider/lwrp_base.rb:87:in `block in action'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/provider.rb:144:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/resource.rb:596:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/runner.rb:74:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/runner.rb:106:in `block (2 levels) in converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/runner.rb:106:in `each'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/runner.rb:106:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/runner.rb:105:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/client.rb:658:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/client.rb:653:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/client.rb:653:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/client.rb:692:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/client.rb:271:in `run'
```

**Comment by mcfiredrill** [comment]
I added `"recipe[firewall::default]"` to my run list to fix it.....

**Comment by kernelsmith** [comment]
you'd think since firewall is a dependency that it would load first no?

**Comment by gravitystorm** [comment]
I'm getting this too - I think this issue should be reopened until a proper fix is found.

**Comment by pierre-pretorius** [comment]
I use chef solo and also had to include firewall::default to fix this issue:

```Ruby
node.default['firewall']['rules'] = [
    {'Allow SSH access' =>
         {'port' => 'ssh'}
    },
    {'Allow HTTP access' =>
         {'port' => 'http'}
    },
    {'Allow HTTPS access' =>
         {'port' => 'https'}
    },
]

include_recipe 'firewall::default'
include_recipe 'ufw'
```
