### ISSUE TITLE
Rules from recipes not working properly

### ISSUE THREAD

**Issue by jesperrojestal** [chef-cookbooks/ufw#21]
Ubuntu 12.10 / Chef 12 / Cookbook checked out from master and v1.0.0

Trying to get ufw::recipes to fetch firewall rules from recipe attributes, since using firewall_rule lwrp from firewall cookbook makes ufw::default rules disappear and be overwritten by the firewall_rule rules.

To reproduce just create a cookbook that sets up node['cookbook_name']['firewall']['rules'] and a run_list with:

``` json
"run_list": [
  "recipe[firewall::default]",
  "recipe[ufw::recipes]",
  "recipe[cookbook_name::default]"
] 
```

and you should get rules installed from the cookbook attributes but instead i get this:

``` shellsession
  NoMethodError
  -------------
  Undefined node attribute or method `concat' on `node'. To set an attribute, use `concat=value' instead.

  Cookbook Trace:
  ---------------
    /var/chef/cache/cookbooks/ufw/recipes/recipes.rb:37:in `block in from_file'
    /var/chef/cache/cookbooks/ufw/recipes/recipes.rb:23:in `each'
    /var/chef/cache/cookbooks/ufw/recipes/recipes.rb:23:in `from_file'

  Relevant File Content:
  ----------------------
  /var/chef/cache/cookbooks/ufw/recipes/recipes.rb:

   30:      node.set['firewall']['rules'].concat(rules) unless rules.nil?
   31:    end
   32:    # get the recipe attributes if there are any
   33:    next unless node[recipe] && node[recipe]['firewall'] && node[recipe]['firewall']['rules']
   34:
   35:    rules = node[recipe]['firewall']['rules']
   36:    Chef::Log.debug "ufw::recipes:#{recipe}:rules #{rules}"
   37>>   node.set['firewall']['rules'].concat(rules) unless rules.nil?
   38:  end
   39:
   40:  # now go apply the rules
   41:  include_recipe 'ufw::default'
   42:
```

Patching line 37 with the following fixes the problem:

``` patch
-node.set['firewall']['rules'].concat(rules) unless rules.nil?
+node.set['firewall']['rules'] = node['firewall']['rules'].to_a.concat(rules) unless rules.nil?
```

**Comment by tas50** [comment]
Fixed on master. Thanks
