### ISSUE TITLE
Databag recipe execution error

### ISSUE THREAD

**Issue by JustDolanIt** [chef-cookbooks/ufw#32]
### Cookbook version
3.1.0

### Chef-client version
13.6.4

### Platform Details
Ubuntu 16.04

### Scenario:
Trying to use **ufw::databag** recipe, but get error on chef run

### Steps to Reproduce:
Create databag item:

```
{
  "id": "test",
  "rules": [
    {"tinc": {
        "port": "655"
    }},
    {"https": {
        "port": "443"
    }}
  ]
}
```

### Expected Result:
Set rules on host with role **test**

### Actual Result:
```
================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/role_infrastructure_scatt/recipes/default.rb
================================================================================

NoMethodError
-------------
undefined method `concat' for {}:Chef::Node::VividMash

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/ufw/recipes/databag.rb:54:in `block in from_file'
  /var/chef/cache/cookbooks/ufw/recipes/databag.rb:47:in `each'
  /var/chef/cache/cookbooks/ufw/recipes/databag.rb:47:in `from_file'
  /var/chef/cache/cookbooks/role_common_scatt/recipes/default.rb:8:in `from_file'
  /var/chef/cache/cookbooks/role_infrastructure/recipes/default.rb:1:in `from_file'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/ufw/recipes/databag.rb:

 47:  rlist.each do |entry|
 48:    Chef::Log.debug "ufw::databag: \"#{entry}\""
 49:    next unless fw_db.member?(entry)
 50:
 51:    # add the list of firewall rules to the current list
 52:    item = data_bag_item('firewall', entry)
 53:    rules = item['rules']
 54>>   node.normal['firewall']['rules'].concat(rules) unless rules.nil?
 55:  end
 56:
 57:  # now go apply the rules
 58:  include_recipe 'ufw::default'
 59:

System Info:
------------
chef_version=13.6.4
platform=ubuntu
platform_version=16.04
ruby=ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
program_name=chef-client worker: ppid=11672;start=11:20:49;
executable=/opt/chef/bin/chef-client
```

**Comment by JustDolanIt** [comment]
Also tried **ufw::recipes** and received same problem:

**attributes/default.rb:**
```
default['role_infrastructure']['firewall']['rules'] = [
    {"tinc" => {
        "port" => "655"
    }},
    {"https" => {
        "port" => "443"
    }}
]
```

**chef-client run log:**
```
================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/role_infrastructure_scatt/recipes/default.rb
================================================================================

NoMethodError
-------------
undefined method `concat' for {}:Chef::Node::VividMash

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/ufw/recipes/recipes.rb:37:in `block in from_file'
  /var/chef/cache/cookbooks/ufw/recipes/recipes.rb:23:in `each'
  /var/chef/cache/cookbooks/ufw/recipes/recipes.rb:23:in `from_file'
  /var/chef/cache/cookbooks/role_common_scatt/recipes/default.rb:8:in `from_file'
  /var/chef/cache/cookbooks/role_infrastructure_scatt/recipes/default.rb:1:in `from_file'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/ufw/recipes/recipes.rb:

 30:      node.normal['firewall']['rules'].concat(rules) unless rules.nil?
 31:    end
 32:    # get the recipe attributes if there are any
 33:    next unless node[recipe] && node[recipe]['firewall'] && node[recipe]['firewall']['rules']
 34:
 35:    rules = node[recipe]['firewall']['rules']
 36:    Chef::Log.debug "ufw::recipes:#{recipe}:rules #{rules}"
 37>>   node.normal['firewall']['rules'].concat(rules) unless rules.nil?
 38:  end
 39:
 40:  # now go apply the rules
 41:  include_recipe 'ufw::default'
 42:

System Info:
------------
chef_version=13.6.4
platform=ubuntu
platform_version=16.04
ruby=ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
program_name=chef-client worker: ppid=14175;start=11:48:28;
executable=/opt/chef/bin/chef-client


Running handlers:
[2017-11-14T11:48:37+03:00] ERROR: Running exception handlers
Running handlers complete
[2017-11-14T11:48:37+03:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources would have been updated
[2017-11-14T11:48:37+03:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2017-11-14T11:48:37+03:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-11-14T11:48:37+03:00] ERROR: undefined method `concat' for {}:Chef::Node::VividMash
[2017-11-14T11:48:37+03:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by SAShapeShifter** [comment]
Im getting the same result.
Where you able to fix the problem.

**Comment by ervinb** [comment]
The patch above should fix this issue.
